language: php

php:
  - 5.6
  - 7.1
  - 7.2

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BUILD_DIR=$TRAVIS_BUILD_DIR

before_install:
  - cd ${TRAVIS_BUILD_DIR}

install:
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - vendor/bin/phpcs --config-set installed_paths ${TRAVIS_BUILD_DIR}/vendor/drupal/coder/coder_sniffer

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
